# Only run thie if go-ci.yml is successful
name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Go app build and run CI"]
    branches: [ "main" ]
    types:
      - completed

#
jobs:
  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Check name & password
      run: echo AA${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} BB$DOCKER_USERNAME
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_ACCESS_TOKEN
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/go-app:latest
        build-args: |
          COMMIT_SHA=${{ github.sha }}
          BRANCH=${{ github.ref }}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          VERSION=1.0.0
        context: .
        file: ./Dockerfile
