name: This is a test workflow when release is created

on:
  workflow_dispatch:
    # inputs:
    #   release:
    #     description: 'Release version'
    #     required: true
    #     default: '1.0.0'
  release:
    types: [published]

jobs:
  my-test-job:
    name: My test job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # with:
      #   token: ${{ secrets.TESTPAT }}

    - name: Test print something
      run: echo "This is a test workflow when release is created"

    - name: Test print tag
      run: echo "Tag is ${{ github.ref_name }}"

  build-and-push-docker-image-latest:
    # Only run this job if the workflow_run job (go-ci) is successful
    if : github.event.my-test-job.conclusion == 'success'

    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/go-app:${{ github.ref_name }}-release
          ${{ secrets.DOCKER_USERNAME }}/go-app:latest
        build-args: |
          COMMIT_SHA=${{ github.sha }}
          BRANCH=${{ github.ref }}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          VERSION=${{ github.ref_name }}
        context: .
        file: ./Dockerfile
