name: On Git tag - Build and push Docker image to Docker Hub

on:
  push :
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Github Event
      run: |
        echo "Github Event is ${{ toJson(github.event) }}"

    - name: Get Github toJson
      run: echo "Github is ${{ toJson(github) }}"

    - name: Get Github Reference
      run: echo "Github Ref is ${{ toJson(github.ref) }}"

    - name: Test print label
      run: echo "Label is ${{ steps.metadata.outputs.labels }}"

    - name: Test print tag
      run: echo "Tag is ${{ github.ref }}"

    - name: Test print tag 2
      run: echo "Tag 2 is ${{ steps.metadata.outputs.tags }}"

    - name: Test print tag 3
      run: echo "Tag 3 is ${{ github.refs.tags }}"

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Login to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    # - name: Build and push Docker image to Docker Hub
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKER_USERNAME }}/go-app:${{ github.sha }}
    #       ${{ secrets.DOCKER_USERNAME }}/go-app:latest
    #     build-args: |
    #       COMMIT_SHA=${{ github.sha }}
    #       BRANCH=${{ github.ref }}
    #       BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    #       VERSION=1.0.0
    #     context: .
    #     file: ./Dockerfile
